### ISSUE TITLE
Can't create model

### ISSUE THREAD

**Issue by kuehnna** [kuehnna/RosettaCM-Nikolas#1]
When I try to run the (adapted) run_cm.sh, I get the following error (Don't know whether the block in the middle is relevant):

> ERROR: HBond evaluation data line does not have enough fields
Expected '17' tokens but found '15' tokens.
hbdon_NONE,hbacc_NONE,seq_sep_other,fade_none,fade_zero,fade_xH,fade_xD,fade_zero,poly_AHdist_w_1p96,poly_cosBAH_off,poly_cosBAH_off,poly_AHD_1j,poly_AHD_1j,hbw_SR_BB,

ERROR:: Exit from: src/core/scoring/hbonds/HBondDatabase.cc line: 441
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libprotocols_d.5.so(print_backtrace(char const*)+0x2b) [0x2b66ed9d9b0b]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libutility.so(utility::exit(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int)+0x186) [0x2b66faca5e36]

/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::hbonds::HBondDatabase::initialize_HBEval()+0x3074) [0x2b66f7599b54]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::hbonds::HBondDatabase::initialize()+0x2b) [0x2b66f75a2deb]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::hbonds::HBondDatabase::HBondDatabase(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x783) [0x2b66f75a35b3]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::hbonds::HBondDatabase::get_database(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x118) [0x2b66f75a3a78]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::hbonds::HBondEnergy::HBondEnergy(core::scoring::hbonds::HBondOptions const&)+0xec) [0x2b66f75b928c]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::hbonds::HBondEnergyCreator::create_energy_method(core::scoring::methods::EnergyMethodOptions const&) const+0x2a) [0x2b66f75b93ca]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::ScoringManager::energy_method(core::scoring::ScoreType const&, core::scoring::methods::EnergyMethodOptions const&) const+0x49) [0x2b66f7bc7d29]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::ScoreFunction::set_weight(core::scoring::ScoreType const&, double const&)+0xbf) [0x2b66f7b69d4f]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::ScoreFunction::_add_weights_from_stream(std::istream&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x951) [0x2b66f7b6b701]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::ScoreFunction::_add_weights_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0x4f) [0x2b66f7b6d2af]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::ScoreFunction::add_weights_from_file(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)+0x63) [0x2b66f7b6d343]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::ScoreFunctionFactory::create_score_function(utility::options::OptionCollection const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, utility::vector1<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0xc60) [0x2b66f7bb33d0]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::ScoreFunctionFactory::create_score_function(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, utility::vector1<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::allocator<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > const&)+0x16) [0x2b66f7bb4636]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::get_score_function(utility::options::OptionCollection const&, bool)+0x14fd) [0x2b66f7bb5b3d]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libcore.3.so(core::scoring::get_score_function(bool)+0x14) [0x2b66f7bb7584]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libprotocols.1.so(protocols::rosetta_scripts::RosettaScriptsParser::generate_mover_for_protocol(core::pose::Pose&, bool&, std::shared_ptr<utility::tag::Tag const>)+0x4fd) [0x2b66f56c3b5d]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libprotocols.1.so(protocols::rosetta_scripts::RosettaScriptsParser::generate_mover_from_pose(std::shared_ptr<protocols::jd2::Job const>, core::pose::Pose&, std::shared_ptr<protocols::moves::Mover>&, bool, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)+0x35e) [0x2b66f56c9e2e]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libprotocols.1.so(protocols::jd2::Parser::generate_mover_from_job(std::shared_ptr<protocols::jd2::Job>, core::pose::Pose&, std::shared_ptr<protocols::moves::Mover>&, bool, bool, bool)+0x35c) [0x2b66f57f195c]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libprotocols.1.so(protocols::jd2::JobDistributor::run_one_job(std::shared_ptr<protocols::moves::Mover>&, long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, unsigned long&, unsigned long&, bool)+0x129a) [0x2b66f57a21aa]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libprotocols.1.so(protocols::jd2::JobDistributor::go_main(std::shared_ptr<protocols::moves::Mover>)+0x186) [0x2b66f57a3f96]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/build/src/release/linux/2.6/64/x86/gcc/5.2/default/libprotocols.1.so(protocols::jd2::FileSystemJobDistributor::go(std::shared_ptr<protocols::moves::Mover>)+0x47) [0x2b66f576cc87]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/bin/rosetta_scripts.linuxgccrelease() [0x407348]
/lib64/libc.so.6(__libc_start_main+0xfd) [0x3c3b21ed5d]
/dors/meilerlab/apps/rosetta/rosetta-3.8/main/source/bin/rosetta_scripts.linuxgccrelease() [0x4074d1]

Error: ERROR: Exception caught by JobDistributor while trying to get pose from job 'S_0001'
Error: 

[ERROR] EXCN_utility_exit has been thrown from: src/core/scoring/hbonds/HBondDatabase.cc line: 441
ERROR: HBond evaluation data line does not have enough fields
Expected '17' tokens but found '15' tokens.
hbdon_NONE,hbacc_NONE,seq_sep_other,fade_none,fade_zero,fade_xH,fade_xD,fade_zero,poly_AHdist_w_1p96,poly_cosBAH_off,poly_cosBAH_off,poly_AHD_1j,poly_AHD_1j,hbw_SR_BB,

Error: Treating failure as bad input; canceling similar jobs
protocols.jd2.FileSystemJobDistributor: job failed, reporting bad input; other jobs of same input will be canceled: S_0001
protocols.jd2.JobDistributor: no more batches to process... 
protocols.jd2.JobDistributor: 1 jobs considered, 1 jobs attempted in 6 seconds
Error: ERROR: Exception caught by rosetta_scripts application:1 jobs failed; check output for error messages
Error:

**Comment by vuoanh** [comment]
So you still use Brian's copy of Rosetta?

**Comment by vuoanh** [comment]
Ah, there are 2 problems. The error message that you encountered is due to the fact that you were still using old version of rosetta database (hint: look at the options file). After you fix your first bug, the second bug will give you a more obvious error message.
